item {
      id: 1
      name: 'Human'
}
item {
     id: 2
     name: 'Car'
}
item {
     id: 3
     name: 'Truck'
}

item {
     id: 4
     name: 'Van'
}
item {
     id: 5
     name: 'Motorbike'
}
item {
     id: 6
     name: 'Bicycle'
}

item {
     id: 7
     name: 'Bus'
}
item {
     id: 8
     name: 'Trailer'
}
